#pragma once

#include "app_listener.h"

#ifndef INV_LN2
#define INV_LN2 1.44269504f
#endif

#ifndef SQRT_LN2
#define SQRT_LN2 0.832554611f
#endif

#ifndef clamp
#define clamp(x,a,b) (min(max(x, a), b))
#endif

#define MAX_HBAO_STEP_SIZE 8
#define NUM_HBAO_PERMUTATIONS (MAX_HBAO_STEP_SIZE)

// NVSDK_HALF_RES_AO renders the AO with a half-res viewport, taking as input half-res linear depths (faster).
// NVSDK_FULL_RES_AO renders the AO with a full-res viewport, taking as input full-res linear depths (higher quality).
enum hbao_resolution_mode_enum
{
    e_half_res_ao,
    e_full_res_ao
};

struct hbao_app_params
{
    float radius;                           // default = 1.0                    // the actual eye-space AO radius is set to radius*SceneScale
    unsigned int step_size;                 // default = 4                      // step size in the AO pass // 1~16
    float angle_bias;                       // default = 10 degrees             // to hide low-tessellation artifacts // 0.0~30.0
    float stength;                          // default = 1.0                    // scale factor for the AO, the greater the darker
    float power_exponent;                   // default = 1.0                    // the final AO output is pow(AO, powerExponent)
    unsigned int blur_radius;               // default = 16 pixels              // radius of the cross bilateral filter // 0~16
    float blur_sharpness;                   // default = 8.0                    // the higher, the more the blur preserves edges // 0.0~16.0
    hbao_resolution_mode_enum m_ao_res_mode;// default = e_full_res_ao
    bool use_blending;                      // default = true                   // to multiply the AO over the destination render target
};  

class c_hbao_params_constant_buffer; 
typedef boost::shared_ptr<c_hbao_params_constant_buffer> params_cb_ptr; 
class c_hbao_input_depth_info; 
typedef boost::shared_ptr<c_hbao_input_depth_info> input_depth_info_ptr; 
class c_hbao_input_normal_info;
typedef boost::shared_ptr<c_hbao_input_normal_info> input_normal_info_ptr;
class c_hbao_input_color_info;
typedef boost::shared_ptr<c_hbao_input_color_info> input_color_info_ptr;

class c_hbao_renderer_options;
typedef boost::shared_ptr<c_hbao_renderer_options> renderer_options_ptr;
class c_hbao_render_targets; 
typedef boost::shared_ptr<c_hbao_render_targets> render_targets_ptr;

class c_hbao_renderer_component : public c_demo_app_listener
{
    typedef c_demo_app_listener super; 

public:
    c_hbao_renderer_component(float fovy);

    virtual HRESULT on_create_resource(const render_sys_context_ptr& render_sys_context);
    virtual void on_release_resource();
    
    // ---------------------------------------------------------------------
    /* 
    Compile the effect
    */ 
    // ---------------------------------------------------------------------
    HRESULT compile_effects();
    HRESULT create_params_cb(); 
   
    void init_ao_params();
    void set_viewport(int width, int height);

	// ---------------------------------------------------------------------
	/*
	Update the hardware constant buffer 
	*/ 
	// ---------------------------------------------------------------------
    void set_ao_parameters(hbao_app_params& params);
    
    // ---------------------------------------------------------------------
    /* 
    Set the input depth buffer for AO rendering, called EVERY FRAME!
        - Set the constant buffer data (not updating the subresource)
        - Set the input depth buffer resolution (width, height and sample count)
        - Careful  with format of the shader resource view. 
    */ 
    // ---------------------------------------------------------------------
    void set_normal_depth_for_ao(texture_2d_ptr& input_normal, texture_2d_ptr& input_depth, float z_near, float z_far, float z_min, float z_max, float scene_scale);
	void set_color_info(texture_2d_ptr& color_tex); 

    // ---------------------------------------------------------------------
    /*
    Linearize the input depth-stencil texture 
    Input: 
        Non-linear depth texture generated by the scene rendering. 
        The non-linear depth buffer is passed in by c_hbao_renderer_component::set_depth_for_ao() 
            which is called in onFrameRender() 
            
    Output: 
        Linear depth texture
    */
	//

    // ---------------------------------------------------------------------
    /*
    // Input: Linear depth buffer 
    // Output: AO Buffer
    */
    // ---------------------------------------------------------------------
    void render_ao(float fovy); 

	texture_2d_ptr& get_ao_render_target(); 
	texture_2d_ptr& get_resolved_normal_tex();
	texture_2d_ptr& get_resolved_depth_tex();
	texture_2d_ptr& get_resolved_color_tex();

    //////////////////////////////////////////////////////////////////////////
    // Effect 
    d3dx11_effect_ptr m_hbao_effect; 
    effect_params_table_ptr m_hbao_effect_var_table;
    ID3DX11EffectTechnique *m_hbao_default_tech;
    ID3DX11EffectConstantBuffer *m_hbao_effect_params_cb; 
	ID3DX11EffectShaderResourceVariable *m_input_normal_tex_sr; 
    ID3DX11EffectShaderResourceVariable *m_input_depth_tex_sr;
	ID3DX11EffectShaderResourceVariable *m_input_random_tex_sr;

	d3dx11_effect_ptr m_linearize_non_msaa_depth_effect; 
	effect_params_table_ptr m_linearize_non_msaa_depth_effect_var_table; 
	ID3DX11EffectTechnique *m_linearize_non_msaa_depth_tech; 
	ID3DX11EffectShaderResourceVariable *m_non_linear_depth_tex_sr; 
	ID3DX11EffectConstantBuffer *m_lin_depth_params_cb_a;
	
	d3dx11_effect_ptr m_resolve_linearize_nd_effect; 
	effect_params_table_ptr m_resolve_linearize_nd_var_table;
	ID3DX11EffectTechnique *m_resolve_linearize_nd_tech; 
	ID3DX11EffectShaderResourceVariable *m_non_linear_msaa_depth_tex_sr; 
	ID3DX11EffectShaderResourceVariable *m_normal_msaa_tex_sr; 
	ID3DX11EffectConstantBuffer *m_lin_depth_params_cb_b;
	
    //////////////////////////////////////////////////////////////////////////
    // Resource as input for HBAO shaders
	//////////////////////////////////////////////////////////////////////////
	
	// ---------------------------------------------------------------------
	/*
		Random texture 
	*/ 
	// ---------------------------------------------------------------------
	texture_2d_ptr m_random_texture;
    
    // ---------------------------------------------------------------------
    /*
        The constant buffer
    */ 
    // ---------------------------------------------------------------------
	hbao_app_params m_cached_ao_params;
    params_cb_ptr m_params_cb;
    
    // ---------------------------------------------------------------------
    /*
        HBAO renderer input textures (non-linear depth buffer rendered by scene renderer)
    */ 
    // ---------------------------------------------------------------------
    input_depth_info_ptr m_input_depth_info;
	input_normal_info_ptr m_input_normal_info; 
    input_color_info_ptr m_input_color_info; 
    // ---------------------------------------------------------------------
    /* 
        HBAO renderer settings 
    */ 
    // ---------------------------------------------------------------------
    renderer_options_ptr m_renderer_options;
    
    // ---------------------------------------------------------------------
    /*
        The output texture of render_ao()
    */ 
    // ---------------------------------------------------------------------
    render_targets_ptr m_render_targets;    

    // Viewport
    D3D11_VIEWPORT m_full_viewport;

private:
	
    void apply_render_ao();

	// ---------------------------------------------------------------------
	/*
	Resolve and linearize the input depth buffer
	Input: 
		Non-linear depth texture generated by the scene rendering. 
		The non-linear depth buffer is passed in by c_hbao_renderer_component::set_depth_for_ao() 
		which is called in onFrameRender() 

	Output: 
		Linear depth texture
	*/ 
	// ---------------------------------------------------------------------
	void apply_resolve_linearize_normal_depth_msaa(); 

	void apply_linearize_depth_non_msaa(); 

	void create_random_texture2();
}; 

typedef boost::shared_ptr<c_hbao_renderer_component> hbao_component_ptr; 
